apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-your-ruby-app-service
spec:
  selector:
    app: {{ .Release.Name }}-your-ruby-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

