apiVersion: v1
kind: Service
metadata:
  name: your-ruby-app-service
  namespace: arun
spec:
  selector:
    app: your-ruby-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
